### ISSUE TITLE
Issue tracker samenvoegen

### ISSUE THREAD

**Issue by brussee** [csrdelft/csrdelft.nl#57]
Er is een enorme versplintering ontstaan vorig jaar:
- [x] Trac tickets https://trac.knorrie.org/csrdelft.nl/report/4
- [x] Trac roadmap https://trac.knorrie.org/csrdelft.nl/roadmap
- [x] Inkworks issues http://git.inkworks.nl/csr/csrdelft.nl/issues
- [x] Inkworks milestones http://git.inkworks.nl/csr/csrdelft.nl/issues/milestones
- [x] Trello agile ?

~~Github issues https://github.com/csrdelft/balins-adventure/issues~~
~~Github milestones https://github.com/csrdelft/balins-adventure/milestones~~

**Comment by thervh70** [comment]
Balins adventure staat compleet los van dit project (bevat wel mooie future ideas, dus ik laat hem nog even staan)

Voor Trac ga ik Knorrie contacten, die is namelijk dood (503)

@brussee kun je me nog iets vertellen over trello agile? Ik heb geen idee wat je daarmee bedoeld.

**Comment by thervh70** [comment]
Inkworks is neergehaald door Am. o.t. pubcie praeses en hij heeft geen backups meer. Dus helaas.

Dat betekent wel dat dit actiepuntje is afgerond.
